Repository PADO-PickAndDeploy/Pado-Backend, pull requests merged in 2025-08, with the labels that each got.

#4 Feature/init
  .github/workflows/dev.yml
  .gitignore
  api-server/build.gradle
  api-server/src/main/java/org/pado/api/PadoServerApplication.java
  api-server/src/main/java/org/pado/api/domain/common/BaseTimeEntity.java
  api-server/src/main/java/org/pado/api/domain/component/Component.java
  api-server/src/main/java/org/pado/api/domain/component/ComponentRepository.java
  api-server/src/main/java/org/pado/api/domain/component/ComponentSubType.java
  api-server/src/main/java/org/pado/api/domain/component/ComponentType.java
  api-server/src/main/java/org/pado/api/domain/connection/Connection.java
  api-server/src/main/java/org/pado/api/domain/connection/ConnectionRepository.java
  api-server/src/main/java/org/pado/api/domain/credential/Credential.java
  api-server/src/main/java/org/pado/api/domain/credential/CredentialRepository.java
  api-server/src/main/java/org/pado/api/domain/project/Project.java
  api-server/src/main/java/org/pado/api/domain/project/ProjectRepository.java
  api-server/src/main/java/org/pado/api/domain/user/User.java
  api-server/src/main/java/org/pado/api/domain/user/UserRepository.java
  api-server/src/main/resources/application.yaml
  api-server/src/test/java/org/pado/api/PadoServerApplicationTests.java
Labels: enhancement

#5 Fix: Update dev CI/CD pipeline to ensure proper environment variable …
  .github/workflows/dev.yml
Labels: hotfix

#16 Feat: Implement comprehensive exception handling system with custom e…
  api-server/src/main/java/org/pado/api/core/exception/CustomException.java
  api-server/src/main/java/org/pado/api/core/exception/ErrorCode.java
  api-server/src/main/java/org/pado/api/core/exception/ErrorResponseDto.java
  api-server/src/main/java/org/pado/api/core/exception/GlobalExceptionHandler.java
Labels: enhancement

#20 Feature/user 001 01
  api-server/src/main/java/org/pado/api/controller/AuthController.java
  api-server/src/main/java/org/pado/api/domain/user/User.java
  api-server/src/main/java/org/pado/api/dto/request/SignupRequest.java
  api-server/src/main/java/org/pado/api/dto/response/SignupResponse.java
  api-server/src/main/java/org/pado/api/service/AuthService.java
Labels: enhancement

#21 Feature/USER-001-02
  api-server/src/main/java/org/pado/api/controller/AuthController.java
  api-server/src/main/java/org/pado/api/dto/request/UserLoginRequest.java
  api-server/src/main/java/org/pado/api/dto/response/UserLoginResponse.java
  api-server/src/main/java/org/pado/api/service/AuthService.java
Labels: enhancement

#22 Feature/USER-001-03
  api-server/src/main/java/org/pado/api/controller/AuthController.java
  api-server/src/main/java/org/pado/api/service/AuthService.java
Labels: enhancement

#23 Feature/USER-001
  .github/workflows/dev-pull.yml
  .github/workflows/dev.yml
  api-server/build.gradle
  api-server/src/main/java/org/pado/api/controller/AuthController.java
  api-server/src/main/java/org/pado/api/core/config/CorsConfig.java
  api-server/src/main/java/org/pado/api/core/config/RedisConfig.java
  api-server/src/main/java/org/pado/api/core/config/SecurityConfig.java
  api-server/src/main/java/org/pado/api/core/security/jwt/JwtAuthenticationEntryPoint.java
  api-server/src/main/java/org/pado/api/core/security/jwt/JwtAuthenticationFilter.java
  api-server/src/main/java/org/pado/api/core/security/jwt/JwtUtil.java
  api-server/src/main/java/org/pado/api/core/security/jwt/RedisTokenBlacklistService.java
  api-server/src/main/java/org/pado/api/core/security/jwt/TokenBlacklistService.java
  api-server/src/main/java/org/pado/api/core/security/jwt/TokenResponse.java
  api-server/src/main/java/org/pado/api/core/security/userdetails/CustomUserDetails.java
  api-server/src/main/java/org/pado/api/core/security/userdetails/CustomUserDetailsService.java
  api-server/src/main/java/org/pado/api/domain/user/Role.java
  api-server/src/main/java/org/pado/api/domain/user/User.java
  api-server/src/main/java/org/pado/api/domain/user/UserRepository.java
  api-server/src/main/java/org/pado/api/dto/request/SigninRequest.java
  api-server/src/main/java/org/pado/api/dto/request/SignupRequest.java
  api-server/src/main/java/org/pado/api/dto/response/DefaultResponse.java
  api-server/src/main/java/org/pado/api/dto/response/SigninResponse.java
  api-server/src/main/java/org/pado/api/dto/response/SignupResponse.java
  api-server/src/main/java/org/pado/api/service/AuthService.java
  api-server/src/main/resources/application.yaml
  api-server/src/test/java/org/pado/api/PadoServerApplicationTests.java
Labels: enhancement

#26 feat: implements SwaggerConfig
  api-server/src/main/java/org/pado/api/core/config/SwaggerConfig.java
Labels: enhancement

#31 feat: Add HashiCorp Vault integration for credential management
  api-server/src/main/java/org/pado/api/controller/CredentialController.java
  api-server/src/main/java/org/pado/api/core/vault/config/VaultConfig.java
  api-server/src/main/java/org/pado/api/core/vault/service/CredentialVaultService.java
  api-server/src/main/java/org/pado/api/core/vault/service/VaultService.java
  api-server/src/main/java/org/pado/api/domain/credential/Credential.java
  api-server/src/main/java/org/pado/api/domain/credential/CredentialRepository.java
  api-server/src/main/java/org/pado/api/service/CredentialService.java
  api-server/src/main/resources/application.yaml
  api-server/src/test/java/org/pado/api/PadoServerApplicationTests.java
  api-server/src/test/java/org/pado/api/TestVaultConfig.java
Labels: enhancement

#32 feat: Implement credential registration
  api-server/src/main/java/org/pado/api/controller/CredentialController.java
  api-server/src/main/java/org/pado/api/domain/credential/Credential.java
  api-server/src/main/java/org/pado/api/dto/request/CredentialRegisterRequest.java
  api-server/src/main/java/org/pado/api/dto/response/CredentialResponse.java
  api-server/src/main/java/org/pado/api/service/CredentialService.java
Labels: enhancement

#34 Hotfix/#33
  .github/workflows/dev-pull.yml
  api-server/src/main/resources/application.yaml
Labels: hotfix

#35 feat: Enhance CI pipeline with improved service health checks and env…
  .github/workflows/dev.yml
Labels: hotfix

#37 fix: Update springdoc-openapi dependency version and modify JWT filte…
  api-server/build.gradle
  api-server/src/main/java/org/pado/api/core/security/jwt/JwtAuthenticationFilter.java
Labels: hotfix

#38 fix: Replace scp with rsync for deploying api-server and remove .env …
  .github/workflows/dev.yml
Labels: deploy

#48 Feature/USER-003-01
  api-server/src/main/java/org/pado/api/core/exception/ErrorCode.java
  api-server/src/main/java/org/pado/api/domain/credential/CredentialRepository.java
  api-server/src/main/java/org/pado/api/service/CredentialService.java
Labels: enhancement

#49 refator: add log
  api-server/src/main/java/org/pado/api/service/CredentialService.java
Labels: enhancement

#50 feat: Add credential detail retrieval with Vault data
  api-server/src/main/java/org/pado/api/controller/CredentialController.java
  api-server/src/main/java/org/pado/api/dto/response/CredentialDetailResponse.java
  api-server/src/main/java/org/pado/api/service/CredentialService.java
Labels: enhancement

#54 Feature/project-001
  api-server/src/main/java/org/pado/api/controller/ProjectController.java
  api-server/src/main/java/org/pado/api/domain/component/Component.java
  api-server/src/main/java/org/pado/api/domain/component/ComponentRepository.java
  api-server/src/main/java/org/pado/api/domain/project/ProjectRepository.java
  api-server/src/main/java/org/pado/api/dto/response/ProjectCreateResponse.java
  api-server/src/main/java/org/pado/api/dto/response/ProjectDetailResponse.java
  api-server/src/main/java/org/pado/api/dto/response/ProjectListResponse.java
  api-server/src/main/java/org/pado/api/service/ProjectService.java
Labels: enhancement

#63 Feature/USER-003
  .github/workflows/dev-pull.yml
  .github/workflows/dev.yml
  .gitignore
  api-server/src/main/java/org/pado/api/core/vault/config/VaultConfig.java
  api-server/src/main/resources/application.yaml
Labels: hotfix

#69 feat: add deployment and running status enums for components and proj…
  api-server/src/main/java/org/pado/api/core/exception/ErrorCode.java
  api-server/src/main/java/org/pado/api/domain/component/Component.java
  api-server/src/main/java/org/pado/api/domain/component/ComponentDeploymentStatus.java
  api-server/src/main/java/org/pado/api/domain/component/ComponentRunningStatus.java
  api-server/src/main/java/org/pado/api/domain/project/Project.java
  api-server/src/main/java/org/pado/api/domain/project/ProjectDeploymentStatus.java
  api-server/src/main/java/org/pado/api/domain/project/ProjectRunningStatus.java
  api-server/src/main/java/org/pado/api/dto/response/ComponentCreateResponse.java
  api-server/src/main/java/org/pado/api/dto/response/ProjectCreateResponse.java
  api-server/src/main/java/org/pado/api/dto/response/ProjectDetailResponse.java
  api-server/src/main/java/org/pado/api/dto/response/ProjectListResponse.java
  api-server/src/main/java/org/pado/api/service/ComponentService.java
  api-server/src/main/java/org/pado/api/service/ProjectService.java
Labels: enhancement

#70 feat: AdminController 구현 - 관리자 API 개발 완료
  api-server/src/main/java/org/pado/api/core/admin/AdminController.java
  api-server/src/main/java/org/pado/api/core/admin/AdminService.java
  api-server/src/main/java/org/pado/api/core/admin/dto/request/AdminSignupRequest.java
  api-server/src/main/java/org/pado/api/core/admin/dto/response/AdminSignupResponse.java
  api-server/src/main/java/org/pado/api/core/config/SecurityConfig.java
  api-server/src/main/java/org/pado/api/core/config/SwaggerConfig.java
Labels: enhancement

#74 Feature/USER-003-01
  api-server/src/main/java/org/pado/api/domain/credential/Credential.java
  api-server/src/main/java/org/pado/api/domain/credential/CredentialType.java
Labels: enhancement

#75 Feature/USER-003
  api-server/src/main/java/org/pado/api/core/admin/AdminService.java
  api-server/src/main/java/org/pado/api/core/exception/ErrorCode.java
  api-server/src/main/java/org/pado/api/core/vault/service/CredentialVaultService.java
  api-server/src/main/java/org/pado/api/domain/credential/Credential.java
  api-server/src/main/java/org/pado/api/domain/credential/CredentialRepository.java
  api-server/src/main/java/org/pado/api/domain/credential/CredentialType.java
  api-server/src/main/java/org/pado/api/dto/request/CredentialRegisterRequest.java
  api-server/src/main/java/org/pado/api/dto/response/CredentialDetailResponse.java
  api-server/src/main/java/org/pado/api/dto/response/CredentialResponse.java
  api-server/src/main/java/org/pado/api/service/CredentialService.java
Labels: enhancement
